## Pruebas con numpy

In [1]:
import numpy as np

In [2]:
n = 1000000

In [6]:
arr = np.arange(n)
type(arr)

numpy.ndarray

In [7]:
arr2 = list(range(n))
type(arr2)

list

In [9]:
%%timeit
for _ in range(10): arr_ = arr * 2

12.1 ms ± 387 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
%%timeit
for _ in range(10): arr2_ = [i * 2 for i in arr2]

589 ms ± 15.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
arr_i = np.array([1,4,5,6,7])
arr_i

array([1, 4, 5, 6, 7])

In [12]:
arr_f = np.array([1,4,5.5,6,7])
arr_f

array([1. , 4. , 5.5, 6. , 7. ])

In [13]:
arr_f.dtype

dtype('float64')

In [16]:
arr_c = np.array([1,4,5.5,6,7+2j])
arr_c

array([1. +0.j, 4. +0.j, 5.5+0.j, 6. +0.j, 7. +2.j])

In [17]:
arr_c.dtype

dtype('complex128')

In [18]:
arr_c.shape

(5,)

In [19]:
m = np.arange(20).reshape(4,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
m.shape

(4, 5)

In [21]:
m.ndim

2

In [22]:
m = np.arange(60).reshape(3,4,5)
m

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [23]:
arr = np.array(['1','2','4','7'], dtype=np.int16)
arr

array([1, 2, 4, 7], dtype=int16)

In [24]:
arr2 = arr.astype(np.float32)
arr2

array([1., 2., 4., 7.], dtype=float32)

In [26]:
m = np.empty((8,5))
m = m * 100
m

array([[9.08814617e-310, 9.08813894e-310, 6.95177503e-308,
        1.28841650e-301, 4.51644679e+259],
       [7.89819104e-305, 9.08814610e-310, 7.89814348e-305,
        9.08814645e-310, 9.08780833e-310],
       [7.57491783e-307, 1.16968885e+216, 1.58020099e-311,
        1.48580779e-198, 5.39948460e-311],
       [4.09487469e-306, 1.33360304e+243, 5.67421675e-309,
        3.57269797e-261, 1.79209176e-311],
       [1.59166660e-306, 1.33360295e+243, 7.84714043e-309,
        3.42196482e-208, 4.33848671e-311],
       [1.68400738e-017, 1.10811151e-300, 1.74956895e-310,
        1.45860545e-301, 2.78138510e-307],
       [2.78138476e-307, 1.15646466e-277, 1.85926288e-176,
        2.32205015e-099, 1.83971785e-070],
       [1.00876644e-301, 1.52177878e-094, 9.97313036e-090,
        6.01346930e-152, 7.89508009e-305]])

In [27]:
unos = np.ones_like(m)
unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
m=np.identity(5)
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
m > 0

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [32]:
m1 = np.arange(24).reshape(4,6)
m2 = np.arange(24).reshape(6,-1)
m1 @ m2

array([[ 220,  235,  250,  265],
       [ 580,  631,  682,  733],
       [ 940, 1027, 1114, 1201],
       [1300, 1423, 1546, 1669]])

In [33]:
m3 = np.arange(24).reshape(4,6)
m1 + m3

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46]])

In [34]:
m3[m3 > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23])

In [35]:
m3[(m3 > 5) & (m3 < 10)]

array([6, 7, 8, 9])

In [36]:
m3[(m3 > 5) & (m3 < 10)]=0

In [37]:
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 0,  0,  0,  0, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
m3[[0,2]]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17]])

In [39]:
m3[0]

array([0, 1, 2, 3, 4, 5])

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[:3]

array([0, 1, 2])

In [42]:
arr[-1]

9

In [43]:
arr = np.arange(25).reshape(5,-1)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr[1:-1,1:-1]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [45]:
arr.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [47]:
L = list(range(10))
a = np.sqrt(L)
b = np.sqrt(tuple(L))
a

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [48]:
b

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [49]:
x = np.random.randn(5)
x = x * 10
x

array([  8.67435333,  -3.06460263,   7.54512377, -10.90011712,
        -3.05533726])

In [50]:
y = np.random.randn(5)
y = y * 10
y

array([-13.03366802, -10.24013625,   7.78359467,  -9.45913931,
         6.4513658 ])

In [51]:
np.maximum(x,y)

array([ 8.67435333, -3.06460263,  7.78359467, -9.45913931,  6.4513658 ])

In [52]:
np.minimum(x,y)

array([-13.03366802, -10.24013625,   7.54512377, -10.90011712,
        -3.05533726])

In [53]:
print(x)
x2 = np.ceil(x)
print(x2)

[  8.67435333  -3.06460263   7.54512377 -10.90011712  -3.05533726]
[  9.  -3.   8. -10.  -3.]


In [54]:
np.floor(x)

array([  8.,  -4.,   7., -11.,  -4.])

In [58]:
x2 = np.array(range(len(x)))
x2 = x2 * -1
np.copysign(x, x2)

array([  8.67435333,  -3.06460263,  -7.54512377, -10.90011712,
        -3.05533726])

In [59]:
m = np.arange(25).reshape(5,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
m.sum(axis=0)

array([50, 55, 60, 65, 70])

In [61]:
m.sum()

300

In [62]:
m.sum(axis=1)

array([ 10,  35,  60,  85, 110])

Generar una matriz aleatoria y contar 