## Pruebas con numpy 2

In [1]:
import numpy as np

In [2]:
m = np.random.randint(1,10,(5,4))
m

array([[9, 8, 3, 5],
       [4, 8, 7, 8],
       [4, 3, 3, 3],
       [8, 4, 3, 1],
       [6, 1, 6, 5]])

In [3]:
m.sum()

99

In [4]:
# Sumas por filas
m.sum(axis=0)

array([31, 24, 22, 22])

In [5]:
# Sumas por cols.
m.sum(axis=1)

array([25, 27, 13, 16, 18])

In [7]:
m.mean()

4.95

In [20]:
m = np.random.randn(20)
m = m * 10
m

array([ -0.21191763,  16.06520047, -13.79998606,  -3.3234671 ,
        -5.11569628, -14.56974448,  -6.35694703,  -4.08268504,
       -10.8965205 ,  12.84783422,   8.40338874,   2.42426618,
         5.51042441,  -5.69843128,   9.59787411, -21.5029803 ,
        17.45446235,   2.25046621, -14.83298766,   0.37255666])

In [21]:
m > 0

array([False,  True, False, False, False, False, False, False, False,
        True,  True,  True,  True, False,  True, False,  True,  True,
       False,  True])

In [22]:
(m > 0).sum()

9

In [23]:
np.amin(m), np.argmin(m)

(-21.502980296355737, 15)

In [24]:
np.amax(m), np.argmax(m)

(17.454462354802583, 16)

In [25]:
(m > 0).any()

True

In [18]:
x = np.random.randint (0, 50,1000)
y = x + np.random.normal (0, 10,1000)
m2 = np.corrcoef(x,y)[0,1]
m2= round(m*100,2)
m2

83.03

In [26]:
m = np.random.randint(0,15,(4,7))
m

array([[11, 10, 11,  8,  2, 14,  9],
       [10, 13,  3, 13, 11,  4, 14],
       [ 2, 13, 12, 14,  2,  8,  7],
       [ 6, 11,  9, 11,  2, 11,  9]])

In [28]:
m.sort()
m

array([[ 2,  8,  9, 10, 11, 11, 14],
       [ 3,  4, 10, 11, 13, 13, 14],
       [ 2,  2,  7,  8, 12, 13, 14],
       [ 2,  6,  9,  9, 11, 11, 11]])

In [29]:
m.sort(0) # Por filas
m

array([[ 2,  2,  7,  8, 11, 11, 11],
       [ 2,  4,  9,  9, 11, 11, 14],
       [ 2,  6,  9, 10, 12, 13, 14],
       [ 3,  8, 10, 11, 13, 13, 14]])

In [30]:
np.unique(m)

array([ 2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
m = np.random.randint(0,15,(40,55))
m2 = np.random.randint(16,30,(40,55))
np.save("matrices",(m,m2))

In [32]:
a,b = np.load("matrices.npy")

In [34]:
a

array([[11,  6,  7, ..., 12,  1,  5],
       [ 8, 13,  4, ..., 10,  6,  0],
       [ 8,  8, 11, ...,  1, 11, 10],
       ...,
       [10,  8,  5, ...,  9,  0, 11],
       [ 4, 13,  9, ...,  4,  3,  9],
       [ 5, 12, 12, ..., 14, 14,  8]])

In [35]:
b

array([[21, 17, 26, ..., 26, 28, 29],
       [24, 21, 16, ..., 24, 29, 29],
       [18, 25, 28, ..., 22, 20, 29],
       ...,
       [29, 29, 29, ..., 22, 26, 19],
       [28, 27, 17, ..., 17, 21, 22],
       [29, 24, 19, ..., 23, 28, 26]])

In [37]:
np.savetxt("matrices.csv", m, delimiter=';', fmt="%d")

In [38]:
np.savez_compressed('matrices.npz',k1=a,k2=b)

In [40]:
dic = np.load('matrices.npz')
m3 = dic['k2']
m3

array([[21, 17, 26, ..., 26, 28, 29],
       [24, 21, 16, ..., 24, 29, 29],
       [18, 25, 28, ..., 22, 20, 29],
       ...,
       [29, 29, 29, ..., 22, 26, 19],
       [28, 27, 17, ..., 17, 21, 22],
       [29, 24, 19, ..., 23, 28, 26]])

In [41]:
m3.ravel()

array([21, 17, 26, ..., 23, 28, 26])

In [43]:
a = np.arange(30).reshape(6,-1)
a.shape

(6, 5)

In [44]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])