## Pruebas con la librería numpy

In [6]:
import numpy as np
from datetime import datetime

In [3]:
%%timeit

my_arr = np.arange(1000000)
for _ in range(10): my_arr2 = my_arr * 2

13.5 ms ± 234 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%%timeit
my_list = list(range(1000000))
for _ in range(10): my_list2 = [x*2 for x in my_list]

620 ms ± 16.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
t1 = datetime.now()
my_arr = np.arange(1000000)
for _ in range(10): my_arr2 = my_arr * 2
t2 = datetime.now()
t2-t1

datetime.timedelta(microseconds=13962)

In [8]:
t1 = datetime.now()
my_list = list(range(1000000))
for _ in range(10): my_list2 = [x*2 for x in my_list]
t2 = datetime.now()
t2-t1

datetime.timedelta(microseconds=628470)

In [9]:
a = np.array([1,2,3,4,5.5,2+4j])
a

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5.5+0.j, 2. +4.j])

In [10]:
a.dtype

dtype('complex128')

In [11]:
n = a.astype(np.float32)
n

<ipython-input-11-2896b29def98>:1: ComplexWarning: Casting complex values to real discards the imaginary part
  n = a.astype(np.float32)


array([1. , 2. , 3. , 4. , 5.5, 2. ], dtype=float32)

In [17]:
b = np.array(["1","2","3","4"], dtype=np.int32)
b, b.dtype

(array([1, 2, 3, 4]), dtype('int32'))

In [14]:
b.shape

(4,)

In [15]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
m = np.zeros((3,5,6))
m

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [19]:
m2 = np.ones_like(m)
m2

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
a = np.random.randint(1,10,(4,5))
a

array([[9, 4, 7, 6, 7],
       [9, 5, 8, 1, 4],
       [6, 9, 1, 5, 7],
       [8, 9, 5, 2, 9]])

In [28]:
b = np.random.randint(1,10,(4,5))
b

array([[6, 3, 3, 4, 6],
       [4, 2, 1, 3, 9],
       [2, 5, 4, 3, 3],
       [6, 6, 4, 4, 1]])

In [29]:
a+b

array([[15,  7, 10, 10, 13],
       [13,  7,  9,  4, 13],
       [ 8, 14,  5,  8, 10],
       [14, 15,  9,  6, 10]])

In [30]:
a * 10

array([[90, 40, 70, 60, 70],
       [90, 50, 80, 10, 40],
       [60, 90, 10, 50, 70],
       [80, 90, 50, 20, 90]])

In [32]:
b = b.T
b

array([[6, 4, 2, 6],
       [3, 2, 5, 6],
       [3, 1, 4, 4],
       [4, 3, 3, 4],
       [6, 9, 3, 1]])

In [33]:
a @ b

array([[153, 132, 105, 137],
       [121,  93,  90, 124],
       [128, 121,  97, 121],
       [152, 142, 114, 139]])

In [35]:
a = np.random.randint(1,70,20)
a

array([54, 23, 65,  9, 56, 30, 12,  1, 17, 46, 13, 69, 28, 36, 44, 28,  6,
       23, 69, 54])

In [36]:
a[a > 50]


array([54, 65, 56, 69, 69, 54])

In [37]:
a[a > 50]=50
a

array([50, 23, 50,  9, 50, 30, 12,  1, 17, 46, 13, 50, 28, 36, 44, 28,  6,
       23, 50, 50])

In [38]:
a[(a >= 10) & (a <= 30)]

array([23, 30, 12, 17, 13, 28, 28, 23])

In [39]:
a[:10]

array([50, 23, 50,  9, 50, 30, 12,  1, 17, 46])

In [42]:
a = np.random.randint(1,10,(4,5))
print(a)
print()
b = np.random.randint(1,10,(4,5))
print(b)
print()
print(a > b)

[[6 5 6 8 6]
 [3 6 7 2 5]
 [1 6 5 2 5]
 [2 7 6 3 5]]

[[2 4 1 2 1]
 [6 1 9 9 9]
 [7 9 6 4 1]
 [1 6 9 3 5]]

[[ True  True  True  True  True]
 [False  True False False False]
 [False False False False  True]
 [ True  True False False False]]


In [43]:
m = np.random.randint(1,10,(7,7))
m

array([[8, 5, 8, 4, 3, 6, 6],
       [7, 8, 3, 7, 1, 3, 4],
       [9, 6, 4, 6, 1, 3, 8],
       [9, 3, 9, 7, 6, 7, 4],
       [8, 5, 1, 5, 2, 4, 3],
       [1, 6, 5, 2, 4, 9, 4],
       [3, 1, 6, 6, 8, 3, 8]])

In [44]:
m[1:-1,1:-1]

array([[8, 3, 7, 1, 3],
       [6, 4, 6, 1, 3],
       [3, 9, 7, 6, 7],
       [5, 1, 5, 2, 4],
       [6, 5, 2, 4, 9]])

In [45]:
m = np.random.randint(1,10,(5,5))
m

array([[6, 4, 9, 4, 3],
       [8, 4, 1, 6, 2],
       [7, 6, 4, 7, 1],
       [8, 7, 2, 3, 8],
       [9, 8, 1, 8, 3]])

In [46]:
arr = np.array(["A","B","C","A","A"])
arr == "A"

array([ True, False, False,  True,  True])

In [47]:
m[arr=='A']

array([[6, 4, 9, 4, 3],
       [8, 7, 2, 3, 8],
       [9, 8, 1, 8, 3]])

In [48]:
m[[1,2,3]]

array([[8, 4, 1, 6, 2],
       [7, 6, 4, 7, 1],
       [8, 7, 2, 3, 8]])

In [49]:
m[[0,1],[3,4]]

array([4, 2])

In [50]:
m.sum()

129

In [51]:
np.sum(m)

129

In [53]:
np.exp(a)

array([[4.03428793e+02, 1.48413159e+02, 4.03428793e+02, 2.98095799e+03,
        4.03428793e+02],
       [2.00855369e+01, 4.03428793e+02, 1.09663316e+03, 7.38905610e+00,
        1.48413159e+02],
       [2.71828183e+00, 4.03428793e+02, 1.48413159e+02, 7.38905610e+00,
        1.48413159e+02],
       [7.38905610e+00, 1.09663316e+03, 4.03428793e+02, 2.00855369e+01,
        1.48413159e+02]])

In [54]:
m = np.random.randint(1,10,20)
m

array([6, 2, 5, 4, 2, 7, 2, 4, 1, 1, 5, 7, 1, 2, 2, 3, 2, 8, 6, 2])

In [55]:
m2 = np.random.randint(1,10,20)
m2

array([4, 1, 8, 9, 2, 4, 2, 9, 1, 2, 7, 7, 3, 8, 4, 6, 7, 6, 4, 5])

In [57]:
np.maximum(m, m2)

array([6, 2, 8, 9, 2, 7, 2, 9, 1, 2, 7, 7, 3, 8, 4, 6, 7, 8, 6, 5])

In [58]:
np.minimum(m, m2)

array([4, 1, 5, 4, 2, 4, 2, 4, 1, 1, 5, 7, 1, 2, 2, 3, 2, 6, 4, 2])

In [61]:
n = np.random.randn(20)

In [64]:
n= n * 10
n = np.abs(n)
n

array([ 49.51040296,  39.69031991,  79.39054633, 132.69762966,
        21.73517397, 112.86855889,  34.6774493 , 151.02112425,
        93.60421166,  56.76326136, 110.17825321, 336.83990863,
       115.3019069 ,  96.11133344,  49.81389118,  34.20558854,
       200.67396615,  64.54727031, 121.48190909,  79.25110431])

In [65]:
a = np.round(n,2)

In [66]:
a

array([ 49.51,  39.69,  79.39, 132.7 ,  21.74, 112.87,  34.68, 151.02,
        93.6 ,  56.76, 110.18, 336.84, 115.3 ,  96.11,  49.81,  34.21,
       200.67,  64.55, 121.48,  79.25])

In [67]:
np.ceil(n)

array([ 50.,  40.,  80., 133.,  22., 113.,  35., 152.,  94.,  57., 111.,
       337., 116.,  97.,  50.,  35., 201.,  65., 122.,  80.])

In [68]:
np.floor(n)

array([ 49.,  39.,  79., 132.,  21., 112.,  34., 151.,  93.,  56., 110.,
       336., 115.,  96.,  49.,  34., 200.,  64., 121.,  79.])